spring:
  datasource:
    url: 'jdbc:mysql://piotrsarnecki.com:3306/sarpio_account'
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: sarpio_account
    password: Account1!
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: "org.hibernate.dialect.MySQL8Dialect"
    generate-ddl: true
    show-sql: true
  liquibase:
    change-log: 'classpath:liquibase/liquibase-changeLog.xml'
server:
  port: 8080