eureka:
  instance:
    instance-id: ${spring.application.name}:${random.uuid}
management:
  endpoints:
    web:
      exposure:
        include: '*'
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/sarpio_account
    username: root
    password: password
  application:
    name: account-service
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    generate-ddl: true
    database-platform: "org.hibernate.dialect.MySQL8Dialect"
  liquibase:
    change-log: 'classpath:liquibase/liquibase-changeLog.xml'
