spring:
  application:
    name: config-server
  profiles:
    active: git
  cloud:
    config:
      server:
        default-label: main
        git:
          uri: https://github.com/sarpio/spring_ap_bank.git
          search-paths: configuration
          clone-on-start: true
management:
  endpoints:
    web:
      exposure:
        include: '*'

server:
  port: 8888